title: Andrés Camilo Carvajal Suarez # your name (or website title) here
logo: "/images/profile123.JPG?raw=true" # your photo (or logo) here
description:
  <p align="center">
  <a href="pdf/CV_AC2 (1).pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/andresca94/">LinkedIn</a> |
  <a href="https://github.com/andresca94">GitHub</a>
  </p>
  
  <p align="justify">
   I’m an engineer and developer with academic background in Earth Science and Geotechnical Engineering having experience in Software Development and GIS. 
  My portfolio includes full stack applications using the state of art for Data Science. I’m very interested in topics such as Natural Language Processing and Computer Vision.
  <br><br>
  <br><br>
  </p> 
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
